CREATE TABLE USERS (
  ID VARCHAR(32) NOT NULL,
  USER_NAME VARCHAR (20),
  PASSWORD varchar(50),
  NICK_NAME VARCHAR (20),
  STATUS INT,
  SEX VARCHAR(10),
  AGE INT,
  REMARK VARCHAR(300),
  CONTACTS VARCHAR(100),
  PRIMARY KEY (ID)
);
COMMENT ON COLUMN USERS.ID IS 'ID';
COMMENT ON COLUMN USERS.USER_NAME IS '用户姓名';
COMMENT ON COLUMN USERS.PASSWORD IS '用户密码';
COMMENT ON COLUMN USERS.NICK_NAME IS '昵称';
COMMENT ON COLUMN USERS.STATUS IS '用户状态';
COMMENT ON COLUMN USERS.SEX IS '用户性别';
COMMENT ON COLUMN USERS.AGE IS '用户年龄';
COMMENT ON COLUMN USERS.REMARK IS '备注信息';
COMMENT ON COLUMN USERS.CONTACTS IS '联系方式';

CREATE TABLE PRODUCT (
  ID VARCHAR (32) NOT NULL ,
  PUTAWAY_DATE TIMESTAMP(6),
  KINDS VARCHAR (50),
  PRODUCT_NAME VARCHAR (50),
  PRODUCT_IMAGE_URL VARCHAR (1000),
  STATUS INT,
  PRODUCT_TYPES VARCHAR (100),
  PRODUCER VARCHAR (50),
  ADDRESS VARCHAR(200),
  DESCRIBED VARCHAR(255),
  PRODUCTION_DATE TIMESTAMP(6),
  PRICE DOUBLE(10,2),
  DISCOUNT_PRICE DOUBLE(10,2),
  IS_DISCOUNT INT,
  LIMIT_NUMBER INT,
  KIND_NUMBER INT DEFAULT 1,
  START_DATE TIMESTAMP(6),
  END_DATE TIMESTAMP(6),
  CARRIAGE DOUBLE(10,2),
  IS_GROUP_BUY INT,
  GROUP_BUY_PRICE DOUBLE(10,2),
  GROUP_BUY_PERSON_NUMBER INT,
  START_GROUP_BUY_DATE TIMESTAMP(6),
  END_GROUP_BUY_DATE TIMESTAMP(6),
  KEY_CLASS VARCHAR(40),
  BIG_KEY_CLASS VARCHAR(40),
  KEYWORD VARCHAR (32),
  PRIMARY KEY (ID)
);
COMMENT ON COLUMN PRODUCT.ID IS 'id';
COMMENT ON COLUMN PRODUCT.PUTAWAY_DATE IS '上架日期';
COMMENT ON COLUMN PRODUCT.KINDS IS '类型';
COMMENT ON COLUMN PRODUCT.PRODUCT_NAME IS '商品名称';
COMMENT ON COLUMN PRODUCT.PRODUCT_IMAGE_URL IS '商品图片';
COMMENT ON COLUMN PRODUCT.STATUS IS '标识图片:1--主图;0--副图';
COMMENT ON COLUMN PRODUCT.PRODUCT_TYPES IS '商品型号';
COMMENT ON COLUMN PRODUCT.PRODUCER IS '生产商';
COMMENT ON COLUMN PRODUCT.ADDRESS IS '产地';
COMMENT ON COLUMN PRODUCT.DESCRIBED IS '商品描述';
COMMENT ON COLUMN PRODUCT.PRODUCTION_DATE IS '生产日期';
COMMENT ON COLUMN PRODUCT.IS_GROUP_BUY IS '是否团购';
COMMENT ON COLUMN PRODUCT.GROUP_BUY_PRICE IS '团购价格';
COMMENT ON COLUMN PRODUCT.GROUP_BUY_PERSON_NUMBER IS '几人团';
COMMENT ON COLUMN PRODUCT.START_GROUP_BUY_DATE IS '开团日期';
COMMENT ON COLUMN PRODUCT.END_GROUP_BUY_DATE IS '闭团日期';
COMMENT ON COLUMN PRODUCT.PRICE IS '商品价格';
COMMENT ON COLUMN PRODUCT.DISCOUNTPRICE IS '优惠价格';
COMMENT ON COLUMN PRODUCT.ISDISCOUNT IS '是否优惠';
COMMENT ON COLUMN PRODUCT.LIMIT_NUMBER IS '用餐人数';
COMMENT ON COLUMN PRODUCT.KIND_NUMBER IS '套餐种类，默认为1';
COMMENT ON COLUMN PRODUCT.START_DATE IS '优惠开始日期';
COMMENT ON COLUMN PRODUCT.END_DATE IS '优惠结束日期';
COMMENT ON COLUMN PRODUCT.CARRIAGE IS '运费';
COMMENT ON COLUMN PRODUCT.KEY_CLASS IS '小类别';
COMMENT ON COLUMN PRODUCT.BIG_KEY_CLASS IS '大类别';
COMMENT ON COLUMN PRODUCT.KEYWORD IS '类别名称';



CREATE TABLE SHOPPINGCART (
  ID VARCHAR(32) NOT NULL,
  USER_ID VARCHAR(32),
  PRODUCT_ID VARCHAR(32),
  STATUS INT ,
  PRODUCT_NUMBER INT ,
  PRIMARY KEY (ID),
  KEY USER_ID (USER_ID),
  KEY PRODUCT_ID (PRODUCT_ID),
  CONSTRAINT USER_ID FOREIGN KEY (USER_ID) REFERENCES USERS (ID),
  CONSTRAINT PRODUCT_ID FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (ID)
);
COMMENT ON COLUMN SHOPPINGCART.ID IS '购物车id';
COMMENT ON COLUMN SHOPPINGCART.USER_ID IS '用户id';
COMMENT ON COLUMN SHOPPINGCART.PRODUCT_ID IS '商品id';
COMMENT ON COLUMN SHOPPINGCART.STATUS IS '状态:0--已经付款;1--未付款';
COMMENT ON COLUMN SHOPPINGCART.PRODUCT_NUMBER IS '商品数量';
